[project]
name = "mcp-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "mcp>=1.25.0",
    "pydantic>=2.12.5",
    "pyodbc>=5.3.0",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
]
